<?php
/**
 * OcrApi
 * PHP version 5
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.HTML for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Client\Invoker\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Client\Invoker\ApiException;
use Client\Invoker\Config;
use Client\Invoker\HeaderSelector;
use Client\Invoker\ObjectSerializer;

/**
 * OcrApi Class Doc Comment
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OcrApi
{
    /**
     * @var ClientInterface
     */
    public $client;

    /**
     * @var Config
     */
    public $config;

    /**
     * @param HeaderSelector  $selector
     */
    public function __construct( HeaderSelector $selector = null ) 
    {
        $this->client = Config::getClient();
        $this->config = Config::getConfig();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Config
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation ocrGetRecognizeAndImportToHtml
     *
     * Recognize text from the image file in the storage and import it to HTML format.
     *
     * @param  string $name The image file name. (required)
     * @param  string $ocr_engine_lang OCR engine language - language (optional, default to en)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \Client\Invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function ocrGetRecognizeAndImportToHtml($name, $ocr_engine_lang = 'en', $folder = null, $storage = null)
    {
        list($response) = $this->ocrGetRecognizeAndImportToHtmlWithHttpInfo($name, $ocr_engine_lang, $folder, $storage);
        return $response;
    }

    /**
     * Operation ocrGetRecognizeAndImportToHtmlWithHttpInfo
     *
     * Recognize text from the image file in the storage and import it to HTML format.
     *
     * @param  string $name The image file name. (required)
     * @param  string $ocr_engine_lang OCR engine language - language (optional, default to en)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \Client\Invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function ocrGetRecognizeAndImportToHtmlWithHttpInfo($name, $ocr_engine_lang = 'en', $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->ocrGetRecognizeAndImportToHtmlRequest($name, $ocr_engine_lang, $folder, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ocrGetRecognizeAndImportToHtmlAsync
     *
     * Recognize text from the image file in the storage and import it to HTML format.
     *
     * @param  string $name The image file name. (required)
     * @param  string $ocr_engine_lang OCR engine language - language (optional, default to en)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ocrGetRecognizeAndImportToHtmlAsync($name, $ocr_engine_lang = 'en', $folder = null, $storage = null)
    {
        return $this->ocrGetRecognizeAndImportToHtmlAsyncWithHttpInfo($name, $ocr_engine_lang, $folder, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ocrGetRecognizeAndImportToHtmlAsyncWithHttpInfo
     *
     * Recognize text from the image file in the storage and import it to HTML format.
     *
     * @param  string $name The image file name. (required)
     * @param  string $ocr_engine_lang OCR engine language - language (optional, default to en)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ocrGetRecognizeAndImportToHtmlAsyncWithHttpInfo($name, $ocr_engine_lang = 'en', $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->ocrGetRecognizeAndImportToHtmlRequest($name, $ocr_engine_lang, $folder, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ocrGetRecognizeAndImportToHtml'
     *
     * @param  string $name The image file name. (required)
     * @param  string $ocr_engine_lang OCR engine language - language (optional, default to en)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function ocrGetRecognizeAndImportToHtmlRequest($name, $ocr_engine_lang = 'en', $folder = null, $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling ocrGetRecognizeAndImportToHtml'
            );
        }

        $resourcePath = '/html/{name}/ocr/import';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($ocr_engine_lang !== null) {
            $queryParams['ocrEngineLang'] = ObjectSerializer::toQueryValue($ocr_engine_lang);
        }
        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['multipart/form-data']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['multipart/form-data'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config['defaultUserAgent']) {
            $defaultHeaders['User-Agent'] = $this->config['defaultUserAgent'];
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config['basePath'] . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ocrGetRecognizeAndTranslateToHtml
     *
     * Recognize text from the image file in the storage, import it to HTML format and translate to specified language.
     *
     * @param  string $name The image file name. (required)
     * @param  string $src_lang Source language - also supposed as the OCR engine language. (required)
     * @param  string $res_lang Result language. (required)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \Client\Invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function ocrGetRecognizeAndTranslateToHtml($name, $src_lang, $res_lang, $folder = null, $storage = null)
    {
        list($response) = $this->ocrGetRecognizeAndTranslateToHtmlWithHttpInfo($name, $src_lang, $res_lang, $folder, $storage);
        return $response;
    }

    /**
     * Operation ocrGetRecognizeAndTranslateToHtmlWithHttpInfo
     *
     * Recognize text from the image file in the storage, import it to HTML format and translate to specified language.
     *
     * @param  string $name The image file name. (required)
     * @param  string $src_lang Source language - also supposed as the OCR engine language. (required)
     * @param  string $res_lang Result language. (required)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \Client\Invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function ocrGetRecognizeAndTranslateToHtmlWithHttpInfo($name, $src_lang, $res_lang, $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->ocrGetRecognizeAndTranslateToHtmlRequest($name, $src_lang, $res_lang, $folder, $storage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ocrGetRecognizeAndTranslateToHtmlAsync
     *
     * Recognize text from the image file in the storage, import it to HTML format and translate to specified language.
     *
     * @param  string $name The image file name. (required)
     * @param  string $src_lang Source language - also supposed as the OCR engine language. (required)
     * @param  string $res_lang Result language. (required)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ocrGetRecognizeAndTranslateToHtmlAsync($name, $src_lang, $res_lang, $folder = null, $storage = null)
    {
        return $this->ocrGetRecognizeAndTranslateToHtmlAsyncWithHttpInfo($name, $src_lang, $res_lang, $folder, $storage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ocrGetRecognizeAndTranslateToHtmlAsyncWithHttpInfo
     *
     * Recognize text from the image file in the storage, import it to HTML format and translate to specified language.
     *
     * @param  string $name The image file name. (required)
     * @param  string $src_lang Source language - also supposed as the OCR engine language. (required)
     * @param  string $res_lang Result language. (required)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ocrGetRecognizeAndTranslateToHtmlAsyncWithHttpInfo($name, $src_lang, $res_lang, $folder = null, $storage = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->ocrGetRecognizeAndTranslateToHtmlRequest($name, $src_lang, $res_lang, $folder, $storage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ocrGetRecognizeAndTranslateToHtml'
     *
     * @param  string $name The image file name. (required)
     * @param  string $src_lang Source language - also supposed as the OCR engine language. (required)
     * @param  string $res_lang Result language. (required)
     * @param  string $folder The source image folder. (optional)
     * @param  string $storage The source image storage. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function ocrGetRecognizeAndTranslateToHtmlRequest($name, $src_lang, $res_lang, $folder = null, $storage = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling ocrGetRecognizeAndTranslateToHtml'
            );
        }
        // verify the required parameter 'src_lang' is set
        if ($src_lang === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $src_lang when calling ocrGetRecognizeAndTranslateToHtml'
            );
        }
        // verify the required parameter 'res_lang' is set
        if ($res_lang === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $res_lang when calling ocrGetRecognizeAndTranslateToHtml'
            );
        }

        $resourcePath = '/html/{name}/ocr/translate/{srcLang}/{resLang}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($folder !== null) {
            $queryParams['folder'] = ObjectSerializer::toQueryValue($folder);
        }
        // query params
        if ($storage !== null) {
            $queryParams['storage'] = ObjectSerializer::toQueryValue($storage);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }
        // path params
        if ($src_lang !== null) {
            $resourcePath = str_replace(
                '{' . 'srcLang' . '}',
                ObjectSerializer::toPathValue($src_lang),
                $resourcePath
            );
        }
        // path params
        if ($res_lang !== null) {
            $resourcePath = str_replace(
                '{' . 'resLang' . '}',
                ObjectSerializer::toPathValue($res_lang),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['multipart/form-data']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['multipart/form-data'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config['defaultUserAgent']) {
            $defaultHeaders['User-Agent'] = $this->config['defaultUserAgent'];
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config['basePath'] . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config['debug']) {
            $options[RequestOptions::DEBUG] = fopen($this->config['debugFile'], 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config['debugFile']);
            }
        }

        return $options;
    }
}
