<?php
/**
 * ConversionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Html for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Client\Invoker\Api;

use \Client\Invoker\Config;
use \Client\Invoker\ApiException;
use \Client\Invoker\ObjectSerializer;

/**
 * ConversionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConversionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToImage
     *
     * Convert the HTML document from the storage by its name to the specified image format..
     *
     */
    public function testConversionGetConvertDocumentToImage()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToImageByUrl
     *
     * Convert the HTML page from the web by its URL to the specified image format..
     *
     */
    public function testConversionGetConvertDocumentToImageByUrl()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToPdf
     *
     * Convert the HTML document from the storage by its name to PDF..
     *
     */
    public function testConversionGetConvertDocumentToPdf()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToPdfByUrl
     *
     * Convert the HTML page from the web by its URL to PDF..
     *
     */
    public function testConversionGetConvertDocumentToPdfByUrl()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToXps
     *
     * Convert the HTML document from the storage by its name to XPS..
     *
     */
    public function testConversionGetConvertDocumentToXps()
    {
    }

    /**
     * Test case for conversionGetConvertDocumentToXpsByUrl
     *
     * Convert the HTML page from the web by its URL to XPS..
     *
     */
    public function testConversionGetConvertDocumentToXpsByUrl()
    {
    }

    /**
     * Test case for conversionPutConvertDocumentToImage
     *
     * Convert the HTML document to the specified image format..
     *
     */
    public function testConversionPutConvertDocumentToImage()
    {
    }

    /**
     * Test case for conversionPutConvertDocumentToPdf
     *
     * Convert the HTML document to PDF..
     *
     */
    public function testConversionPutConvertDocumentToPdf()
    {
    }

    /**
     * Test case for conversionPutConvertDocumentToXps
     *
     * Convert the HTML document to XPS..
     *
     */
    public function testConversionPutConvertDocumentToXps()
    {
    }
}
