<?php
/**
 * DocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Html for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Client\Invoker\Api;

use \Client\Invoker\Config;
use \Client\Invoker\ApiException;
use \Client\Invoker\ObjectSerializer;

/**
 * DocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for documentGetDocument
     *
     * Return the HTML document by the name from default or specified storage..
     *
     */
    public function testDocumentGetDocument()
    {
    }

    /**
     * Test case for documentGetDocumentFragmentByXPath
     *
     * Return list of HTML fragments matching the specified XPath query..
     *
     */
    public function testDocumentGetDocumentFragmentByXPath()
    {
    }

    /**
     * Test case for documentGetDocumentImages
     *
     * Return all HTML document images packaged as a ZIP archive..
     *
     */
    public function testDocumentGetDocumentImages()
    {
    }
}
