<?php
/**
 * OcrApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.HTML for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Client\Invoker;

use \Client\Invoker\Configuration;
use \Client\Invoker\ApiException;
use \Client\Invoker\ObjectSerializer;

/**
 * OcrApiTest Class Doc Comment
 *
 * @category Class
 * @package  Client\Invoker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OcrApiTest extends \PHPUnit_Framework_TestCase
{

    protected static $test;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
        $test = new Configuration();
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for ocrGetRecognizeAndImportToHtml
     * @dataProvider providerOcrGetRecognizeAndImportToHtml
     *
     * Recognize text from the image file in the storage and import it to HTML format..
     *
     */
    public function testOcrGetRecognizeAndImportToHtml()
    {
        $this->assertEquals(1, 1);
    }

    public function providerOcrGetRecognizeAndImportToHtml()
    {
        return array(
            array ("test_ocr.png","en"),
            array ("test_ocr.jpg","en")
        );
    }


    /**
     * Test case for ocrGetRecognizeAndTranslateToHtml
     *
     * @dataProvider providerOcrGetRecognizeAndTranslateToHtml
     *
     * Recognize text from the image file in the storage, import it to HTML format and translate to specified language..
     *
     */
    public function testOcrGetRecognizeAndTranslateToHtml()
    {
        $this->assertEquals(1, 1);

    }

    public function providerOcrGetRecognizeAndTranslateToHtml()
    {
        return array(
            array ("test_ocr.png","en","fr"),
            array ("test_ocr.jpg","en", "de")
        );
    }

}
